yolo:
  type: "yolov4_tiny"
  iou_threshold: 0.5
  score_threshold: 0.005
  max_boxes: 10
  strides: "32,16"
  anchors: "9,13 15,29 21,10 25,13 29,11 32,15"
  mask: "3,4,5 0,1,2"
  name_path: "./data/pascal_voc/voc.name"

train:
  label: "signature_yolov4_tiny_SM_DM_CIoU_FL"
  anno_path: "./data/pascal_voc/signature_train.txt"
  image_size: "320,352,384,416,448,480,512,544,576,608"

  batch_size: 12
  init_weight_path: "./ckpts/tmp/voc_yolov4_tiny_SM_DM_CIoU_FL/mAP-0.6906.h5"
  save_weight_path: "./ckpts"

  loss_type: "CIoU+FL"

  mosaic: false
  label_smoothing: false
  normal_method: true

  ignore_threshold: 0.5

test:
  anno_path: "./data/pascal_voc/signature_test.txt"
  image_size: "416"
  batch_size: 8
  init_weight_path: "./ckpts/tmp/signature_yolov4_tiny_SM_DM_CIoU_FL/mAP-0.6906.h5"