yolo:
  type: "yolov4_tiny"
  iou_threshold: 0.5
  score_threshold: 0.005
  max_boxes: 10
  strides: "32,16"
  anchors: "24,28 25,28 32,37 52,59 60,60 60,52"
  mask: "3,4,5 0,1,2"
  name_path: "./data/pascal_voc/voc.name"

train:
  label: "voc_yolov4_tiny_SM_DM_CIoU_FL"
  anno_path: "./data/pascal_voc/train.txt"
  image_size: "320,352,384,416,448,480,512,544,576,608"

  batch_size: 18
  init_weight_path: "./ckpts/tmp/voc_yolov4_tiny_SM_DM_CIoU_FL/202009220214/mAP-0.6091.h5"
  save_weight_path: "./ckpts"

  loss_type: "CIoU+FL"

  mosaic: false
  label_smoothing: false
  normal_method: true

  ignore_threshold: 0.5

test:
  anno_path: "./data/pascal_voc/test.txt"
  image_size: "416"
  batch_size: 6
  init_weight_path: "./ckpts/tmp/voc_yolov4_tiny_SM_DM_CIoU_FL/202009220214/mAP-0.6091.h5"